name: Pipeline Financeiro Diário

on:
  schedule:
    - cron: '0 21 * * 1-5' # Roda às 18:00 BRT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dá permissão para o robô salvar os arquivos .parquet
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pipeline
        run: python analise_acoes.py 

      - name: Arquivar Dados Bronze
        uses: actions/upload-artifact@v4
        with:
          name: dados-bronze
          path: data_lake/bronze/   
          retention-days: 7         # Configuração de auto-delete

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 1. Adiciona TUDO o que foi gerado pelo Python (evita o erro de unstaged changes)
          git add data_lake/gold/*.parquet data_lake/silver/*.parquet logs/*.log
          
          # 2. Tenta commitar. Se não houver nada novo, ele apenas avisa e segue em frente.
          git commit -m "Dados atualizados via Action: $(date +'%Y-%m-%d')" || echo "Sem mudanças para commitar"
          
          # 3. Faz o pull rebase com estratégia de resolução automática
          # O -X ours diz: "Se houver conflito no arquivo de dados, mantenha o que o robô acabou de gerar"
          git pull origin main --rebase -X ours
          
         
          # 4. Envia com segurança
          git push origin main

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: logs/pipeline_analise_acoes.log
          retention-days: 7 # O log apaga sozinho depois de 7 dias
      