name: Pipeline Financeiro Diário

on:
  schedule:
    - cron: '0 21 * * 1-5' # Roda às 18:00 BRT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dá permissão para o robô salvar os arquivos .parquet
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pipeline
        run: python analise_acoes.py # Nome corrigido aqui

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data_lake/
          git commit -m "Dados atualizados via Action: $(date +'%Y-%m-%d')" || exit 0
          git push

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: logs/pipeline_analise_acoes.log
          retention-days: 7 # O log apaga sozinho depois de 7 dias